blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/digitaldesignerjazz/solnet/discussions
    about: Please use Discussions for questions, ideas, and general conversation.
